GestionEquipe/urls.py
from django.conf.urls import url
from django.contrib.auth.decorators import login_required
from . import views


urlpatterns = [
   # url(r'^visualisation$', views.home),
    url(r'^article/(?P<id_article>\d+)$', views.view_article),
    url(r'^GestionEquipe$', views.home, name='GestionEquipe'),
    url(r'^$', views.Accueil, name='Accueil'),
    url(r'^ajax/supprimer/$', views.supprimer, name='supprimer'),
    url(r'^ajax/infoJoueur/$', views.infoJoueur, name='infoJoueur'),
    url(r'^ajax/modifierRemplir/$', views.modifierRemplir, name='modifierRemplir'),
    url(r'^ajax/modifier/$', views.modifier, name='modifier'),
    url(r'^ajouter/$', views.ajouter, name='ajouter'),
    url(r'^classement$', views.classement, name='classement'),
    url(r'^classement$', views.classement, name='classement'),
    url(r'^deconnexion$', views.deconnexion, name='deconnexion'),

    ]

football/urls.py
from django.conf.urls import url, include
from django.contrib import admin
admin.autodiscover()  
#from django.contrib import admin
#from visualisation import views

urlpatterns = [
   # url(r'^admin/', admin.site.urls),
   	url(r'^admin/', include (admin.site.urls)),
    url(r'', include('GestionEquipe.urls')),
    url(r'^GestionEquipe/', include('GestionEquipe.urls')),

]

"""
Liste des applications :
connexion
	- connexion/user
	- connexion/admin
administration
	- ''
visualisation
	-''
	- joueur/id
	- ajouter
	- modifier
	- supprimer
	- systeme 
classements
	- classements/buteurs
	- classements/passeurs


Liste des routes sur tout le projet :
connexion/user
connexion/admin
administration
gestion
classements/buteurs
classements/passeurs


"""

GestionEquipe/models.py
from __future__ import unicode_literals

from django.db import models


class Arbitre(models.Model):
    id_arbitre = models.AutoField(db_column='Id_Arbitre', primary_key=True)  # Field name made lowercase.
    a_nom = models.CharField(db_column='A_Nom', max_length=255)  # Field name made lowercase.
    a_prenom = models.CharField(db_column='A_Prenom', max_length=255)  # Field name made lowercase.
    a_mdp = models.CharField(db_column='A_Mdp', max_length=255)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'arbitre'


class AuthGroup(models.Model):
    name = models.CharField(unique=True, max_length=80)

    class Meta:
        managed = False
        db_table = 'auth_group'


class AuthGroupPermissions(models.Model):
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)
    permission = models.ForeignKey('AuthPermission', models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_group_permissions'
        unique_together = (('group', 'permission'),)


class AuthPermission(models.Model):
    name = models.CharField(max_length=255)
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING)
    codename = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'auth_permission'
        unique_together = (('content_type', 'codename'),)


class AuthUser(models.Model):
    id = models.ForeignKey('Entraineur', models.DO_NOTHING, db_column='id', primary_key=True)
    password = models.CharField(max_length=128)
    last_login = models.DateTimeField(blank=True, null=True)
    is_superuser = models.IntegerField()
    username = models.CharField(unique=True, max_length=150)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    email = models.CharField(max_length=254)
    is_staff = models.IntegerField()
    is_active = models.IntegerField()
    date_joined = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'auth_user'


class AuthUserGroups(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    group = models.ForeignKey(AuthGroup, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_groups'
        unique_together = (('user', 'group'),)


class AuthUserUserPermissions(models.Model):
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)
    permission = models.ForeignKey(AuthPermission, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'auth_user_user_permissions'
        unique_together = (('user', 'permission'),)


class DjangoAdminLog(models.Model):
    action_time = models.DateTimeField()
    object_id = models.TextField(blank=True, null=True)
    object_repr = models.CharField(max_length=200)
    action_flag = models.SmallIntegerField()
    change_message = models.TextField()
    content_type = models.ForeignKey('DjangoContentType', models.DO_NOTHING, blank=True, null=True)
    user = models.ForeignKey(AuthUser, models.DO_NOTHING)

    class Meta:
        managed = False
        db_table = 'django_admin_log'


class DjangoContentType(models.Model):
    app_label = models.CharField(max_length=100)
    model = models.CharField(max_length=100)

    class Meta:
        managed = False
        db_table = 'django_content_type'
        unique_together = (('app_label', 'model'),)


class DjangoMigrations(models.Model):
    app = models.CharField(max_length=255)
    name = models.CharField(max_length=255)
    applied = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_migrations'


class DjangoSession(models.Model):
    session_key = models.CharField(primary_key=True, max_length=40)
    session_data = models.TextField()
    expire_date = models.DateTimeField()

    class Meta:
        managed = False
        db_table = 'django_session'


class Entraineur(models.Model):
    id_entraineur = models.AutoField(db_column='Id_Entraineur', primary_key=True)  # Field name made lowercase.
    e_nom = models.CharField(db_column='E_Nom', max_length=255)  # Field name made lowercase.
    e_prenom = models.CharField(db_column='E_Prenom', max_length=255)  # Field name made lowercase.
    username = models.CharField(max_length=150)
    e_mdp = models.CharField(db_column='E_Mdp', max_length=128)  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'entraineur'


class Equipe(models.Model):
    id_equipe = models.AutoField(db_column='Id_Equipe', primary_key=True)  # Field name made lowercase.
    e_nom = models.CharField(db_column='E_Nom', max_length=255)  # Field name made lowercase.
    id_entraineur = models.ForeignKey(Entraineur, models.DO_NOTHING, db_column='Id_Entraineur')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'equipe'


class Joueur(models.Model):
    id_joueur = models.AutoField(db_column='Id_Joueur', primary_key=True,verbose_name="Id Joueur")  # Field name made lowercase.
    j_nom = models.CharField(db_column='J_Nom', max_length=255,verbose_name="Nom")  # Field name made lowercase.
    j_prenom = models.CharField(db_column='J_Prenom', max_length=255,verbose_name="Prenom")  # Field name made lowercase.
    j_age = models.IntegerField(db_column='J_Age',verbose_name="Age")  # Field name made lowercase.
    j_taille = models.IntegerField(db_column='J_Taille',verbose_name="Taille")  # Field name made lowercase.
    j_poste = models.CharField(db_column='J_Poste', max_length=255,verbose_name="Poste")  # Field name made lowercase.
    j_status = models.CharField(db_column='J_Status', max_length=10,verbose_name="Status")  # Field name made lowercase.
    j_disponible = models.IntegerField(db_column='J_Disponible',verbose_name="Disponible")  # Field name made lowercase.
    j_position = models.IntegerField(db_column='J_Position',verbose_name="Position")  # Field name made lowercase.
    id_equipe = models.ForeignKey(Equipe, models.DO_NOTHING, db_column='Id_Equipe',verbose_name="Nom Equipe")  # Field name made lowercase.
    id_statistique = models.ForeignKey('Statistiques', models.DO_NOTHING, db_column='Id_Statistique', blank=True, null=True,verbose_name="Id Statistique") # Field name made lowercase.
    class Meta:
        managed = False
        db_table = 'joueur'


class Statistiques(models.Model):
    id_statistique = models.AutoField(db_column='Id_Statistique', primary_key=True)  # Field name made lowercase.
    s_but = models.IntegerField(db_column='S_But')  # Field name made lowercase.
    s_passe_decisive = models.IntegerField(db_column='S_Passe_Decisive')  # Field name made lowercase.
    s_carton_jaune = models.IntegerField(db_column='S_Carton_Jaune')  # Field name made lowercase.
    s_carton_rouge = models.IntegerField(db_column='S_Carton_Rouge')  # Field name made lowercase.

    class Meta:
        managed = False
        db_table = 'statistiques'

GestionEquipe/forms.py
from django import forms
from .models import Joueur
from .models import Equipe

class classementForm(forms.ModelForm):
    class Meta:
        model = Joueur
        #fields = '__all__'
        exclude = ['id_joueur']

class modifierForm(forms.ModelForm):

	class Meta:

		model = Joueur
		fields = '__all__'
		exclude = ['id_statistique','id_equipe']

class ajouterForm(forms.ModelForm):

	class Meta:

		model = Joueur
		fields = '__all__'
		exclude = ['id_joueur','id_statistique','id_equipe']
		#exclude = ['status', 'id_equipe','position']

class ConnexionForm(forms.Form):

    username = forms.CharField(label="Nom d'utilisateur", max_length=30)
    password = forms.CharField(label="Mot de passe", widget=forms.PasswordInput)

GestionEquipe/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponse
from django.http import JsonResponse
from django.shortcuts import render
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.conf import settings
from django.contrib.auth import logout
from django.shortcuts import render
from django.core.urlresolvers import reverse

from GestionEquipe.models import Joueur
from GestionEquipe.models import Equipe
from GestionEquipe.models import Statistiques
from GestionEquipe.models import Arbitre
from GestionEquipe.models import Entraineur
from GestionEquipe.models import AuthUser


from pprint import pprint
from django.views.decorators.csrf import csrf_exempt
from .forms import classementForm
from .forms import modifierForm
from .forms import ajouterForm
from .forms import ConnexionForm
from django.contrib.auth import authenticate, login



#test
# Create your views here.

def home(request):
    if request.user.is_authenticated:
        # joueurs = Joueur.objects.all().filter()

        joueurs = Joueur.objects.all().filter(id_equipe=request.user.id)
        formJoueur = modifierForm(request.POST)
        formAjouter= ajouterForm(request.POST)
    else  :
        return HttpResponse("<p>Vous n'etes pas autoriser à acceder à cette page</p>")


    return render(request,'GestionEquipe/visu.html',locals())

def classement(request):

    joueurs = Joueur.objects.all().filter().order_by('nom')
    equipes = Equipe.objects.all()
    statistiques = Statistiques.objects.all()

    form = classementForm(request.POST)
    if form.is_valid():
        form.save()

    return render(request,'GestionEquipe/classement.html',locals())

def view_article(request, id_article):

    """

    Vue qui affiche un article selon son identifiant (ou ID, ici un numéro)

    Son ID est le second paramètre de la fonction (pour rappel, le premier

    paramètre est TOUJOURS la requête de l'utilisateur)

    """

    return render(request,'GestionEquipe/testos.html',locals())

@csrf_exempt
def supprimer(request):
	id=request.POST.get('id', None)
	Joueur.objects.filter(id_joueur=id).delete()
	if request.method== "POST":
		reponse="ok"
		return JsonResponse({'reponse' : 'reponse'})

@csrf_exempt
def infoJoueur(request):
    id=request.POST.get('id', None)
    joueurs = Joueur.objects.all().filter(id_joueur=id)
    for joueur in joueurs:
        nom=joueur.j_nom
        prenom=joueur.j_prenom
        age=joueur.j_age
        taille=joueur.j_taille
        poste=joueur.j_poste
        disponible=joueur.j_disponible
        position=joueur.j_position

    return JsonResponse({
            'id' : id,
            'nom' : nom,
            'prenom' : prenom,
            'age' : age,
            'taille' : taille,
            'poste' : poste,
            'disponible' : disponible,
            'position' :position,
            })


def Accueil(request):

    error = False

    if request.method == "POST":
        form = ConnexionForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data["username"]
            password = form.cleaned_data["password"]
            user = authenticate(username=username, password=password)  # Nous vérifions si les données sont correctes
            if user:  # Si l'objet renvoyé n'est pas None
                login(request, user)  # nous connectons l'utilisateur
            else: # sinon une erreur sera affichée
                error = True
    else:
        form = ConnexionForm()


    return render(request, 'Accueil.html', locals())

def modifierRemplir(request):
    id=request.POST.get('id', None)
    joueurs = Joueur.objects.all().filter(id_joueur=id)
    for joueur in joueurs:
        nom=joueur.j_nom
        prenom=joueur.j_prenom
        age=joueur.j_age
        taille=joueur.j_taille
        poste=joueur.j_poste
        disponible=joueur.j_disponible
        status=joueur.j_status
        position=joueur.j_position

    return JsonResponse({
            'id' : id,
            'nom' : nom,
            'prenom' : prenom,
            'age' : age,
            'taille' : taille,
            'poste' : poste,
            'disponible' : disponible,
            'status': status,
            'position': position,
            })

def modifier(request):
    #id=request.POST.get('donnees', None)
    id_joueur=int(request.POST.get('id_joueur', None))
    formEquipe= modifierForm(request.POST)
    if formEquipe.is_valid():
        testos= Joueur.objects.get(pk=id_joueur)
        test=modifierForm(request.POST, instance = testos)
        test.save()
        reponse="ok"
        return redirect('../../GestionEquipe')
    else:
        return JsonResponse({'reponse' : 'erreur'})

def ajouter(request):
    #id=request.POST.get('donnees', None)
    formAjouter= ajouterForm(request.POST)
    if formAjouter.is_valid():
        formAjouter.save()
        reponse="ok"
    else:
        reponse="nannn"
    return redirect('../../GestionEquipe/GestionEquipe')


def deconnexion(request):
    logout(request)
    return redirect(reverse(Accueil))

#
# class LoginView(TemplateView):
#
#   template_name = '/template/GestionEquipe/Accueil.html'
#
#   def post(self, request, **kwargs):
#
#     username = request.POST.get('username', False)
#     password = request.POST.get('password', False)
#     user = authenticate(username=username, password=password)
#     if user is not None and user.is_active:
#         login(request, user)
#         return HttpResponseRedirect( settings.LOGIN_REDIRECT_URL )
#
#     return render(request, self.template_name)
#
#
# class LogoutView(TemplateView):
#
#   template_name = '/template/GestionEquipe/Accueil.html'
#
#   def get(self, request, **kwargs):
#
#     logout(request)
#
#     return render(request, self.template_name)

GestionEquipe/templates/GestionEquipe/testos.html
<html>
<p> test {{id_article}}</p>
</html>

GestionEquipe/templates/GestionEquipe/visu.html
{% extends "base.html" %}
<!--- pour ajouter des liens il faut les mettres dans base.html qui represente le head  et tout les contenu doivent etre dans block content qui est le body   -->


{% block content %}

{{user.id}}
<h1>Gestion d'équipe</h1>
<br> </br>
<div id="corps">
<section id="composition">
<table class="table table-hover table-dark">
<h2> Titulaires </h2>
    <tr>
        <th> Poste </th>
        <th colspan="2">Nom</th>
    </tr>
{% for joueur in joueurs %}
    {% if joueur.j_status == "Titulaire"%}
    <tr num="{{ joueur.id_joueur }}">
        <td> {{ joueur.j_poste }} </td>
        <td> {{ joueur.j_nom }} </td>

        <!--- <td> {{ joueur.status }} </td> -->

        <td><button id="myInput" type="button" data-toggle="modal" data-target="#myModal" onclick="remplirModifier({{ joueur.id_joueur }})"><i class="fa fa-pencil-square-o" aria-hidden="true" >
        <td><button type="button" value="Supprimer" id="Supprimer" onclick="Supprimer({{ joueur.id_joueur }})"><i class="fa fa-trash" aria-hidden="true"></i></button></td>
        </i></button></td>
        <td><button id="visualisation" onclick="infoJoueur({{ joueur.id_joueur }})"  type="button" data-toggle="modal" data-target="#modalVisu"><i class="fa fa-address-card" aria-hidden="true"></i>
</button></td>
    </tr>
    {% endif %}
{% empty %}

    <p class="empty">Pas de commentaires pour le moment </p>

{% endfor %}

</table>
</section>

<section id="composition">
<table class="table table-hover table-dark">
<h2> Remplaçants </h2>
    <tr>
        <th> Poste </th>
        <th colspan="2">Nom</th>
    </tr>
{% for joueur in joueurs %}
    {% if joueur.j_status == "Remplaçant" %}
    <tr num="{{ joueur.id_joueur }}">
        <td> {{ joueur.j_poste }} </td>
        <td> {{ joueur.j_nom }} </td>
        <!--- <td> {{ joueur.status }} </td> -->

        <td><button type="button" value="Supprimer" id="Supprimer" onclick="Supprimer({{ joueur.id_joueur }})"><i class="fa fa-trash" aria-hidden="true" ></i></button></td>
        <td><button id="myInput" type="button" data-toggle="modal" data-target="#myModal" onclick="remplirModifier({{ joueur.id_joueur }})"><i class="fa fa-pencil-square-o" aria-hidden="true"></i></button></td>
        <td><button id="visualisation" onclick="infoJoueur({{ joueur.id_joueur }})" type="button" data-toggle="modal" data-target="#modalVisu"><i class="fa fa-address-card" aria-hidden="true"></i>
</button></td>
    </tr>
    {% endif %}
{% empty %}

    <p class="empty">Pas de commentaires pour le moment </p>

{% endfor %}
</table>
</section>

<section id="composition">
<table class="table table-hover table-dark">
<h2> Réservistes </h2>
    <tr>
        <th> Poste </th>
        <th colspan="2">Nom</th>
    </tr>
{% for joueur in joueurs %}
    {% if joueur.j_status == "Réserviste" %}
    <tr num="{{ joueur.id_joueur }}">
        <td> {{ joueur.j_poste }} </td>
        <td> {{ joueur.j_nom }} </td>
        <!--- <td> {{ joueur.status }} </td> -->

        <td><button type="button" value="Supprimer" id="Supprimer" onclick="Supprimer({{ joueur.id_joueur }})"><i class="fa fa-trash" aria-hidden="true"></i></button></td>
        <td><button id="myInput" type="button" data-toggle="modal" data-target="#myModal" onclick="remplirModifier({{ joueur.id_joueur }})"><i class="fa fa-pencil-square-o" aria-hidden="true" ></i></button></td>
        <td><button id="visualisation" onclick="infoJoueur({{ joueur.id_joueur }})" type="button" data-toggle="modal" data-target="#modalVisu"><i class="fa fa-address-card" aria-hidden="true"></i>
</button></td>
    </tr>
    {% endif %}
{% empty %}

    <p class="empty">Pas de commentaires pour le moment </p>

{% endfor %}
</table>
</section>


<i class="fa fa-user-plus fa-6" id="add" aria-hidden="true" data-toggle="modal" data-target="#myModalAjouter" ></i>
</div>

<!-- Modal Modifier-->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modifier le joueur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
           <form id="modifierForm" action="{% url "modifier" %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="id_joueur" id="id_id_joueur">
            {{ formJoueur.as_p }}
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        <input class="btn btn-primary" type="submit" value="Enregister" />
        </form>
      </div>
    </div>
  </div>
</div>

<!-- Modal Ajouter-->
<div class="modal fade" id="myModalAjouter" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Ajouter un joueur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
           <form id="ajouterForm" action="{% url "ajouter" %}" method="POST">
            {% csrf_token %}
            <!--<input type="hidden" name="id_joueur" id="id_id_joueur">-->
            {{ formAjouter.as_p }}

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
        <input class="btn btn-primary" type="submit" value="Enregister" />
        </form>
      </div>
    </div>
  </div>
</div>


<!-- Modal Visu-->
<div class="modal fade" id="modalVisu" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Infos joueur</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body" id="blockInfo">

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Fermer</button>
      </div>
    </div>
  </div>
</div>



<script type="text/javascript">
  $('#myModal').on('shown.bs.modal', function () {

  $('#myInput').focus()
})
  // using jQuery
/*function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie !== '') {
        var cookies = document.cookie.split(';');
        for (var i = 0; i < cookies.length; i++) {
            var cookie = jQuery.trim(cookies[i]);
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) === (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
}*


var csrftoken = getCookie('csrftoken');

function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
}
/*$.ajaxSetup({
    beforeSend: function(xhr, settings) {
        if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
            xhr.setRequestHeader("X-CSRFToken", csrftoken);
        }
    }
});*/

//$.ajaxSetup({   headers: {  "X-CSRFToken": csrftoken  }  });

$.ajaxSetup({
     beforeSend: function(xhr, settings) {
         function getCookie(name) {
             var cookieValue = null;
             if (document.cookie && document.cookie != '') {
                 var cookies = document.cookie.split(';');
                 for (var i = 0; i < cookies.length; i++) {
                     var cookie = jQuery.trim(cookies[i]);
                     // Does this cookie string begin with the name we want?
                     if (cookie.substring(0, name.length + 1) == (name + '=')) {
                         cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                         break;
                     }
                 }
             }
             return cookieValue;
         }
         if (!(/^http:.*/.test(settings.url) || /^https:.*/.test(settings.url))) {
             // Only send the token to relative URLs i.e. locally.
             xhr.setRequestHeader("X-CSRFToken", getCookie('csrftoken'));
         }
     }
});

//var csrftoken = jQuery("[name=csrfmiddlewaretoken]").val();

  //$('[num="1"]').attr("color","red");
  function Supprimer(id){  // CLICK SUPPRIMER

    $.ajax({  // AJAX SUPPRESSION
                type: 'POST',
                url: 'ajax/supprimer/',
                data: { 'id' : id},
                dataType: 'json',
                encode: true
            }).done(function(data) {
               $('[num="'+id+'"]').remove();

            });
                        };

function infoJoueur(id){  // CLICK SUPPRIMER

  $.ajax({  // AJAX SUPPRESSION
              type: 'POST',
              url: 'ajax/infoJoueur/',
              data: { 'id' : id},
              dataType: 'json',
              encode: true
          }).done(function(data) {
            $("#blockInfo").empty()
            $("#blockInfo").append("<p>Nom :"+data.nom+"</p>")
            $("#blockInfo").append("<p>Prénom :"+data.prenom+"</p>")
            $("#blockInfo").append("<p>Age :"+data.age+"</p>")
            $("#blockInfo").append("<p>Taille :"+data.taille+"</p>")
            $("#blockInfo").append("<p>Poste :"+data.poste+"</p>")
            $("#blockInfo").append("<p>Position :"+data.position+"</p>")

          });
                      };

function remplirModifier(id){  //
    $.ajax({  //
                type: 'POST',
                url: 'ajax/modifierRemplir/',
                data: { 'id' : id},
                dataType: 'json',
                encode: true
            }).done(function(data) {
                console.log(data)
               //$('#modifierForm').();
               $('#id_id_joueur').val(data.id);
               $('#id_j_nom').val(data.nom);
               $('#id_j_prenom').val(data.prenom);
               $('#id_j_age').val(data.age);
               $('#id_j_taille').val(data.taille);
               $('#id_j_poste').val(data.poste);
               $('#id_j_status').val(data.status);
               $('#id_j_disponible').val(data.disponible);
               $('#id_j_position').val(data.position);
               //$('#id_id_equipe option[value="1"]').prop('selected', true);
            });
                        };


$("#modifForm").submit(function( event ) {
    var donnees=$("#modifForm").serialize();
    console.log(donnees)
  $.ajax({  // AJAX SUPPRESSION
                type: 'POST',
                url: 'ajax/modifier/',
                data: donnees,
                dataType: 'json',
                encode: true
            }).done(function(data) {
                console.log(data)
               $('#id_id_joueur').val(data.id);
               $('#id_nom').val(data.nom);
               $('#id_prenom').val(data.prenom);
               $('#id_age').val(data.age);
               $('#id_taille').val(data.taille);
               $('#id_poste').val(data.poste);
               $('#id_disponible').val(data.disponible);

            });

  event.preventDefault();
});

</script>

{% endblock %}